### ISSUE TITLE
Examples of ESENT Database Replication

### ISSUE THREAD

**Issue by Indhukrishna** [Const-me/EsentSerialize#1]
Can you please share any examples for ESENT database replication?

**Comment by Const-me** [comment]
Hi Indhu.
Sorry to inform you I don’t have examples for that.

A few years ago I’ve completed a project where I developed some server software replicating its ESENT DB across a cluster.

1. The functionality to do bulk IO from the ESENT without [de]serialization, raw read/write API, wasn’t ported from version 2.x of the library. You can get the 2.x version from my old repository: http://esentserialize.codeplex.com/ Porting those two methods should be straightforward, and wont take long. However…
2. ESENT has no support for replicated databases. So, what I did there, I implemented my replication on the upper levels. Unfortunately, that was relatively complex functionality, AFAIR it took me a couple of months to implement and debug (that included networking, service discovery and related things).
3. Finally, some features of ESENT are incompatible with replication. For example, there’s no programmatic way to set auto-increment or version columns. If you are going to replicate your DB, you can’t use the features.

That’s too much work for an unpaid hobby project.
