### ISSUE TITLE
what attribute to use for Lists<T>

### ISSUE THREAD

**Issue by vip32** [Const-me/EsentSerialize#2]
I am trying to add Addresses to the Person class. To serialize them I probably need an attribute but which one is suitable? The idea is to store the addresses as part of the person, no seperate table needed (single document)

![image](https://cloud.githubusercontent.com/assets/164303/19367879/85381c00-919d-11e6-808a-5229492500f5.png)

**Comment by Const-me** [comment]
Hi, Vincent.

You can use data contract serialization for that property.
```
[EseDCS]
public List<Address> Addresses { get; set; }
```
DCS stands for "Data Contract Serializer". The implementation writes to binary XML format, using optional pre-shared dictionary.

A couple more things.

1. For structures like your `Address`, you can increase serialization efficiency (both time and space) 2-3 times by providing a good XML dictionary. There’s an example for that in this repository, in Demos/DictionaryDemo/Dictionary folder.

2. `[EseDCS]` writes a binary blob, opaque for the database engine. You won’t be able to build meaningful index over that column. If you’re OK with that, go on.

But if you need to search (e.g. you expect millions of persons in your DB, and you’ll want to quickly filter them by city or country), this won’t work well. If that’s your case, you can use another table for addresses, with 4 separate columns for your 4 address fields, and secondary indices for search. Or you can keep `[EseDCS]` but **also** add another column, e.g.
```
[EseDCS]
public List<Address> Addresses { get; set; }
[EseMultiText]
public List<string> Countries { get { return Addresses.Select(a=>a.Country).ToList(); } set { } }
```
This adds a multi-valued string column with countries, suitable for indexing.

Regards, Kosta.
